config/routes.rb
Psysite::Application.routes.draw do

  match '/', to: 'menus#index', via: 'post'    

  match '/cases', to: 'menus#index', via: 'get'  
  match '/cases/:id', to: 'menus#show', via: 'get'  
  
  match '/arts', to: 'posts#index', via: 'get'  
  match '/arts/:id', to: 'posts#show', via: 'get'    
  match '/abouts', to: 'bios#show', via: 'get'  
  
  match '/to_pay/:sum', to: 'pays#to_pay', via: 'get'    
  match '/success_pay', to: 'pays#success', via: 'get'      
  match '/pending_pay', to: 'pays#pending', via: 'get'        
  match '/fail_pay', to: 'pays#fail', via: 'get'       
  
  match '/for_pay_click', to: 'pays#for_pay', via: 'get'
  match '/confirm_form/:name/:akey/:id', to: 'pays#after_pay_form', via: 'get'    
  match '/success_confirm', to: 'pays#success_confirm_form', via: 'get'    
  match '/payed/:akey/:id/:akey_payed', to: 'orders#order_is_payed', via: 'get'      

  resources :pays, :orders, :users
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :posts do
    resources :post_comments
  end

  resources :books do
    resources :book_comments
    resources :book_orders    
  end

  resources :consults do
    resources :consult_orders    
  end

  resources :films do
    resources :film_comments
    resources :film_orders    
  end

  root 'menus#index'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  after_create { |admin| admin.send_reset_password_instructions }


end

app/models/bio.rb
#!/bin/env ruby
# encoding: utf-8

class Bio < ActiveRecord::Base

end

app/models/book.rb
#!/bin/env ruby
# encoding: utf-8
class Book < ActiveRecord::Base

  has_many :book_orders
  has_many :book_comments

end

app/models/book_comment.rb
#!/bin/env ruby
# encoding: utf-8
class BookComment < ActiveRecord::Base

  belongs_to :book
  belongs_to :user  

end

app/models/book_order.rb
#!/bin/env ruby
# encoding: utf-8
class BookOrder < ActiveRecord::Base

  belongs_to :book
  belongs_to :user  

end

app/models/consult.rb
#!/bin/env ruby
# encoding: utf-8
class Consult < ActiveRecord::Base

  has_many :consult_orders

end

app/models/consult_order.rb
#!/bin/env ruby
# encoding: utf-8
class ConsultOrder < ActiveRecord::Base

  belongs_to :consult
  belongs_to :user  

end

app/models/film.rb
#!/bin/env ruby
# encoding: utf-8
class Film < ActiveRecord::Base

  has_many :film_orders
  has_many :film_comments

end

app/models/film_comment.rb
#!/bin/env ruby
# encoding: utf-8
class FilmComment < ActiveRecord::Base

  belongs_to :film
  belongs_to :user  

end

app/models/film_order.rb
#!/bin/env ruby
# encoding: utf-8
class FilmOrder < ActiveRecord::Base
  
  belongs_to :film
  belongs_to :user
  
end

app/models/menu.rb
#!/bin/env ruby
# encoding: utf-8
class Menu < ActiveRecord::Base

end

app/models/order.rb
#!/bin/env ruby
# encoding: utf-8
class Order < ActiveRecord::Base

end 

app/models/pay.rb
class Pay < ActiveRecord::Base
end

app/models/post.rb
#!/bin/env ruby
# encoding: utf-8
class Post < ActiveRecord::Base

  has_many :post_comments

  @title='Принять участие в вебинаре'
  @keys='Умиротворение, доброжелательность, подавленность, психология, жить, покое, чувство пустоты, психолог, хочется любви, тепла, сигарета, утешение, полнота, энергия'
  @descr_head='Боль одиночества, внутренней пустоты и обиды мешает работать, верить в счастье, требует утешения едой, сигаретой. И хочется быть любимым, любить'

  @descr_body='Чувство подавленности, дискомфорта, заторможенности, пустоты, неудовлетворенности от пустых взаимоотношений. Хочется радости, безопасности, тепла'
  @h1='Психолог по Skype и E-mail - Хочется почувствовать радость, любовь, доброжелательность, тепло, стать счастливым'

end

app/models/post_comment.rb
#!/bin/env ruby
# encoding: utf-8
class PostComment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user  

end

app/models/review.rb
#!/bin/env ruby
# encoding: utf-8
class Review < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
#!/bin/env ruby
# encoding: utf-8
class User < ActiveRecord::Base

  has_many :book_orders
  has_many :book_comments
  
  has_many :consult_orders
  
  has_many :film_orders
  has_many :film_comments
  
  has_many :post_comments
  
  has_many :reviews

end

app/controllers/bios_controller.rb
# encoding: utf-8
class BiosController < ApplicationController

  before_action :set_post, only: [:show]
  
  def show
  end


  private

  def set_post
    @bio = Bio.find(1)
  end

end

app/controllers/books_controller.rb
# encoding: utf-8
class BooksController < ApplicationController

  before_action :set_post, only: [:show]

  def index
    @books = Book.all
  end
  
  def show
  end


  private

  def set_post
    @book = Book.find(params[:id])
  end

end

app/controllers/pays_controller.rb
class PaysController < ApplicationController

  def for_pay
    @consult = Consult.find(1)    
    #@name = URI.decode(params[:name])
    #@sum = params[:sum].to_s + '.0'        
  end

  def after_pay_form
    @name = params[:name]
    @id = params[:id]
    @akey = params[:akey]
    if Order.where(id: @id).empty? or Order.find(@id).akey != @akey
      redirect_to '/'
    else
      @order = Order.find(@id)
    end  
  end

  def success_confirm_form
  end   

  def to_pay     
  end
  
  def success
  end  

  def pending
  end

  def fail
  end

end

app/views/layouts/clients/_table_number.html.haml
#table_clients
  = link_to menus_path do
    %table.bordered
      %thead
        %tr
          %th #
          %th IMDB Top 10 Movies
          %th Year
      %tr
        %td
          0:00
          .table_number_select
            ВЫБРАТЬ
        %td
          8:00
          .table_number_select
            ВЫБРАТЬ
        %td
          16:00
          .table_number_select
            ВЫБРАТЬ

      %tr
        %td
          1:00
          .table_number_select
            ВЫБРАТЬ
        %td
          9:00
          .table_number_select
            ВЫБРАТЬ
        %td
          17:00
          .table_number_select
            ВЫБРАТЬ
      %tr
        %td
          2:00
          .table_number_select
            ВЫБРАТЬ
        %td
          10:00
          .table_number_select
            ВЫБРАТЬ
        %td
          18:00
          .table_number_select
            ВЫБРАТЬ
      %tr
        %td
          3:00
          .table_number_select
            ВЫБРАТЬ
        %td
          11:00
          .table_number_select
            ВЫБРАТЬ
        %td
          19:00
          .table_number_select
            ВЫБРАТЬ
      %tr
        %td
          4:00
          .table_number_select
            ВЫБРАТЬ
        %td
          12:00
          .table_number_select
            ВЫБРАТЬ
        %td
          20:00
          .table_number_select
            ВЫБРАТЬ
      %tr
        %td
          5:00
          .table_number_select
            ВЫБРАТЬ
        %td
          13:00
          .table_number_select
            ВЫБРАТЬ
        %td
          21:00
          .table_number_select
            ВЫБРАТЬ
      %tr
        %td
          6:00
          .table_number_select
            ВЫБРАТЬ
        %td
          14:00
          .table_number_select
            ВЫБРАТЬ
        %td
          22:00
          .table_number_select
            ВЫБРАТЬ
      %tr
        %td
          7:00
          .table_number_select
            ВЫБРАТЬ
        %td
          15:00
          .table_number_select
            ВЫБРАТЬ
        %td
          23:00
          .table_number_select
            ВЫБРАТЬ

app/views/layouts/content/_content.html.haml
#main_content.row-fluid

  - if @menu_up_item == 'menus_main' or @menu_up_item == 'bio' 
    = image_tag 'psychologist.png', alt: 'Фото психолога', class: 'span4' ' offset2', id: 'psychologist', title: 'Психолог', alt: 'Психолог : <<Приглашаю присесть рядом>>'

  
    - if @menu_up_item == 'menus_main'
    
      #button_and_menu.span6.offset5
        =yield


    - if @menu_up_item == 'bio'    
    
      #button_and_menu.span7.offset5
        =yield        


  - else

    =yield        
  

    -##button_and_menu.span5
        

app/views/layouts/content/_form_pay(копия).html.haml
    - if @addresser.errors.any?
      = javascript_include_tag 'auto_focus'
      :css
        #button INPUT {
          margin-bottom: 4px !important;
        }

        #button {
          margin-top: 30px !important;
        }

        .my-input-xlarge {
          color: #ef0041 !important;
        }

      - if @addresser.name != ''  
        - @input_value_name = @addresser.name
      - else
        - @input_value_name = 'сюда'

      - if @addresser.word != ''  
        - @input_value_word = @addresser.word
      - else
        - @input_value_word = 'сюда'

      - if @addresser.email != ''  
        - @input_value_email = @addresser.email
      - else
        - @input_value_email = 'сюда'

      %p#errors_style
        .row-fluid
          .span5.offset3
            .label_words
              .errors_style{style: 'font-size: 110%;'}
                Пожалуйста,
        .row-fluid
          .span5.offset3
            .label_words
              .errors_style
                напишите

          - if flash[:email]
            - @email_class = 'errors_field'
            - flash[:email] = nil
          - if flash[:name]
            - @name_class = 'errors_field'
            - flash[:name] = nil
          - if flash[:word] == :word
            - flash[:word]
            - flash[:word] = nil

          -# @addresser.errors.each do |attribute, msg|
            - if attribute == :email
              - @email_class = 'errors_field'
            - if attribute == :name
              - @name_class = 'errors_field'
            - if attribute == :word
              - @word_class = 'errors_field'
            -#%li
              = msg
          -# errors.clear    


    .row-fluid
      .span10.offset2
        - unless @addresser.errors.any?
          - @input_value_name = 'сюда'
          - @input_value_word = 'сюда'
          - @input_value_email = 'сюда'
          .row-fluid
            .span6
              .label_words
                Напишите

        .row-fluid
          .span6
            .label_words
              Ваше имя:

app/views/layouts/content/_form_pay.html.haml
#button.margin_bottom.form_fond
  - @user = User.new
  = form_for @user do |f|   
     

    -# @addresser.link = @product.link
    -# @addresser.has_to_pay = @product.price
    -# @addresser.title = @product.name     
    
    -#= @addresser.typ or 'notype'
    -#= @addresser.link or 'nolink' 
    -#= @addresser.has_to_pay or 'nopay' 
    -#= @addresser.pp_id or 'noid' 
    -#= @addresser.title or 'notitle'  
    
    -#= f.hidden_field :typ, value: @addresser.typ    
    -#= f.hidden_field :pp_id, value: @addresser.pp_id
    -#= f.hidden_field :link, value: "#{@addresser.link or 'no_link'}"    
    -#= f.hidden_field :has_to_pay, value: "#{@addresser.has_to_pay or 'no_has_to_pay'}"    
    -#= f.hidden_field :title, value: @addresser.title
    
     
    - @input_value_name = 'сюда'
    - @input_value_word = 'сюда'
    - @input_value_email = 'сюда'     
    
    - @write_word = true
     
    - if flash[:name_error] or flash[:email_error] or flash[:word_error] or flash[:use_for_news_error]
      - @write_word = false
      = javascript_include_tag 'auto_focus'                
      
      - if flash[:name] != ''  
        - @input_value_name = flash[:name]
      - else
        - @input_value_name = 'сюда'

      - if flash[:word] != ''  
        - @input_value_word = flash[:word]
      - else
        - @input_value_word = 'сюда'

      - if flash[:email] != ''  
        - @input_value_email = flash[:email]
      - else
        - @input_value_email = 'сюда'           
        
      
      - if flash[:name_error] or flash[:email_error] or flash[:word_error]
        %p#errors_style
          .row-fluid
            .span5.offset3
              .label_words
                .errors_style
                  Пожалуйста,
          .row-fluid
            .span5.offset3
              .label_words
                .errors_style{style: 'font-size: 110%;'}
                  напишите
                  
      - if flash[:use_for_news_error]
        %p#errors_style
          .row-fluid
            .span5.offset3
              .label_words
                .errors_style
                  Пожалуйста,
          .row-fluid
            .span5.offset3
              .label_words
                .errors_style{style: 'font-size: 100%;'}
                  подтвердите ещё раз                  
                  
                  

      - if flash[:name_error]
        - @name_class = 'errors_field'
        - flash[:name_error] = nil
      - if flash[:email_error]
        - @email_class = 'errors_field'
        - flash[:email_error] = nil
      - if flash[:word_error] 
        - @word_class = 'errors_field'
        - flash[:word_error] = nil
      - if flash[:use_for_news_error]  
        - @use_for_news_class = 'errors_field'
        - flash[:use_for_news_error] = nil
            
    %div{id: "#{@use_for_news_class}"}
    .row-fluid
      .span12
        - if @write_word   
          .row-fluid
            .span6
              .label_words
                Напишите

        .row-fluid
          .span6
            .label_words
              Ваше имя:                  
          .span6{style: 'margin-top: -3px;'}
            = f.text_field :name, {class: 'input-address' ' input-xlarge' ' my-input-xlarge' " #{@name_class}", type: 'text', value: "#{@input_value_name}", 'data-maxsize' => '60', spellcheck: 'false', onfocus: "if (this.value == 'сюда') {this.value = '';}", onblur: "if (this.value == '') {this.value = 'сюда';}"}
            - @name_class = nil

        .row-fluid
          .span6
            .label_words{style: 'margin-left: -6px;'}
              Число '#{$form_control_digit}':
          .span6{style: 'margin-top: -3px; margin-left: 4px;'}
            = f.text_field :word, {class: 'input-address' ' input-xlarge' ' my-input-xlarge' " #{@word_class}", type: 'text', value: "#{@input_value_word}", 'data-maxsize' => '60', spellcheck: 'false', onfocus: "if (this.value == 'сюда') {this.value = '';}", onblur: "if (this.value == '') {this.value = 'сюда';}"}
            - @word_class = nil

        .row-fluid
          .span6
            .label_words{style: 'margin-left: 2px;'}
              Ваш E-mail:
          .span6{style: 'margin-top: -3px; margin-left: 1px !important;'}
            = f.text_field :email, {class: 'input-address' ' input-xlarge' ' my-input-xlarge' " #{@email_class}", type: 'text', value: "#{@input_value_email}", 'data-maxsize' => '60', spellcheck: 'false', onfocus: "if (this.value == 'сюда') {this.value = '';}", onblur: "if (this.value == '') {this.value = 'сюда';}"}


            - @email_class = nil

        - unless flash[:name_error] or flash[:email_error] or flash[:word_error] or flash[:use_for_news_error]
          .div_around_submit_button
            #top_field{style: 'width: 70%;'}
              = flash[:notise]

        -# @addresser = nil
        - @input_value_name = nil
        - @input_value_word = nil
        - @input_value_email = nil   


        .div_around_submit_button{style: 'width: 70%;'}
          #email_security
            #{image_tag ('form/form_security.png')} Для Вашей безопасности
            %br/
            Ваш E-mail не будет виден посетителям сайта

        - unless @addresser_type == 'post'
          .div_around_submit_button{style: 'width: 70%;'}
            = label_tag :use_for_news, id: 'form_pay_checkbox_label' do
              = f.check_box :use_for_news, {id: 'form_pay_checkbox', checked: true}
              Да, я хочу получать новые статьи и видео семинары на свой E-mail
              
        
        -#= hidden_field_tag(:type, "#{@addresser_type}")
        -#-# post
        -#- if @addresser_pp_id
        -#  = hidden_field_tag(:pp_id, "#{@addresser_pp_id}")
        -#-# product   
        -#- if @addresser_link
        -#  = hidden_field_tag(:link, "#{@addresser_link}")
        -#- if @addresser_has_to_pay
        -#  = hidden_field_tag(:has_to_pay, "#{@addresser_has_to_pay}")
        -#- if @addresser_title
        -#  = hidden_field_tag(:title, "#{@addresser_title}")                              
          
        - @adderesser_type = nil
        - @adderesser_pp_id = nil
        - if @addresser_link
          - @addresser_link = nil
        - if @addresser_has_to_pay            
          - @addresser_has_to_pay = nil
        - if @addresser_title        
          - @addresser_title = nil

        - flash[:name_error] = nil
        - flash[:email_error] = nil
        - flash[:word_error] = nil
        - flash[:use_for_news_error] = nil
        - flash[:name] = nil
        - flash[:email] = nil
        - flash[:word] = nil



        .div_around_submit_button
          = f.submit 'Да, всё так!!!', {class: ' btn-primary ' ' btn ' ' btn-large ' ' my-btn ' ' my-btn-large ', title: 'Нажать на кнопку' }

app/views/layouts/fond/_author.html.haml
%ul#author
  %li
    %u
      %b Автор сайта (design by):
  %li
    vitalina.liane@gmail.com
  /%li
  /  %a{href: '#', title: 'Посмотреть на работы автора'}
  /    http://here.im/

%a{href: 'https://plus.google.com/100311678738539067775?rel=author'}
  Google

app/views/layouts/fond/_bread.html.haml
#bread{'xmlns:v' => 'http://rdf.data-vocabulary.org/#'}
  %span{typeof: 'v:Breadcrumb'}
    %a{href: 'http://psysite.herokuapp.com.com/', property: 'v:title', rel: 'v:url'} Психолог по Skype и E-mail
    ›

app/views/layouts/fond/_fond.html.haml
#fond_part
  #fond_h_org_author
    = render partial: 'layouts/fond/org'
    = render partial: 'layouts/fond/author'
  #fond_imgs_min
    = render partial: 'layouts/fond/bread'
    = render partial: 'layouts/fond/social'
    = render partial: 'layouts/fond/imgs_min'

#fond_green
- if @menu_up_item == 'menus_main'
  = image_tag 'forest/forest_original.jpg', id: 'forest_img', alt: 'Умиротворяющий лес'
- else
  = image_tag 'forest/forest_blur75.jpg', id: 'forest_img', alt: 'Умиротворяющий лес'

app/views/layouts/fond/_imgs_min.html.haml
%div{itemscope: '', itemtype: 'http://schema.org/ImageObject'}
  %div{itemprop: 'name'}
    %strong Умиротворение
  %span{itemprop: 'alternativeHeadline'}
    %em Комфорт
  = image_tag 'fond/forest_min.jpg', itemprop: 'contentURL', width: '200px', height: '96px', alt: 'Превью фона сайта - умиротворяющего леса'
  %meta{content: 'true', itemprop: 'isFamilyFriendly'}/

  %div{itemprop: 'keywords'}
    %u
      %em Умиротворение, ощущение равновесия, психолог, внутренняя гармония, комфорт, удовольствие, советы психолога, консультация,онлайн, семейный психолог, практический психолог, практичного, сайт, скайп, видеочат, видео чат
  %div{itemprop: 'description'}
    %b
      Пейзаж создает ощущение комфорта, тепла, покоя, равновесия и внутренней гармонии, к которым приходит клиент в результате общения с психологом
  %span{itemprop: 'about'}
    %b
      Чувство тепла
-# END_forest_min


%div{itemscope: '', itemtype: 'http://schema.org/ImageObject'}
  %div{itemprop: 'name'}
    %strong Психолог
  %span{itemprop: 'alternativeHeadline'}
    %em Доброжелательность
  = image_tag 'fond/psychologist_min.jpg', itemprop: 'contentURL', width: '120px', height: '136px', alt: 'Превью фото психолога'
  %meta{content: 'true', itemprop: 'isFamilyFriendly'}/

  %div{itemprop: 'keywords'}
    %u
      %em Почувствовать доброжелательность, отношения, эмоции, тепло, расположение, психолог, принятие, радость, психолог практик, помощь, профессиональный, нужен психолог, летом, хороший, рекомендации
  %div{itemprop: 'description'}
    %b
      Образ человека позволяет клиенту почувствовать доброжелательное к нему отношение, эмоциональное тепло, безопасность, расположение и принятие
  %span{itemprop: 'about'}
    %b
      Ощущение радости
-# END_sit_min

app/views/layouts/fond/_org.html.haml
%div{itemscope: '', itemtype: 'http://schema.org/Organization'}
  %h1
    = @h1
  %div{itemprop: 'description'}
    %b
      = @descr_body
  / END_body_description

  %nav#menu_list
    %ul
      %li
        %a{href: 'main'}
          %strong
            Главная
    %p
      В какой сфере хотите
      %strong
        изменений
    %ul
      %li
        %a{href: 'life'}
          %strong
            Личная жизнь
      %li
        %a{href: 'creation'}
          %strong
            Стать более
            %em продуктивным
      %li
        %a{href: 'habit'}
          %strong
            Избавиться от
            %em привычки
            курить, переедать и т.п.
  / END_menu_list
  %div
    у психолога, психотерапия, депрессия, psiholog, онлайн консультация

  %a{href: 'http://happy-vita.com/', itemprop: 'url'}
  %div{itemprop: 'name'}
    %strong
      %em Психолог онлайн
      по
      %em Skype
      и
      %em E-mail
  %a{href: 'fond/forest_min.jpg', itemprop: 'image'}
    Logo
  %div{itemprop: 'founder'} Татьяна
  %i Связаться:
  %br/
  %strong Skype:
  %span{itemprop: 'faxNumber'} Bereg.Beseda
  %br/
  %strong E-mail:
  %span{itemprop: 'email'} bereg.beseda@ukr.net
/ END_text_contacts

#copyright
  %strong
    \© 2013
    %em Все права защищены.
    Авторские права на контент сайта принадлежат владельцу сайта.
    Полное или частичное копирование материалов сайта преследуется по закону <<Об авторском праве>>
  / END_rights_part

/ END_schema_org

app/views/layouts/fond/_social.html.haml
#social
  %a{href: 'https://www.facebook.com/pages/Психолог-по-Skype-и-E-mail-онлайн/163688777155871'}
    = image_tag 'social/faceb.jpg', alt: 'Facebook, Фейсбук'
  %a{href: 'https://plus.google.com/communities/114445997222416340514'}
    = image_tag 'social/goo.jpg', alt: 'Google+, Гугл Плюс'
  %a{href: 'http://beregbeseda.livejournal.com/'}
    = image_tag 'social/livej.jpg', alt: 'LifeJournal, Живой Журнал, ЖЖ'
  %a{href: 'http://my.mail.ru/community/psycholog_skype/'}
    = image_tag 'social/mail.jpg', alt: 'MailRu, Меил Ру'
  %a{href: 'http://www.odnoklassniki.ru/group/51711407882385'}
    = image_tag 'social/odn.jpg', alt: 'Odnoklassniki, Одноклассники'
  = link_to image_tag('social/vk.jpg', alt: 'Vkontakte, vk, В контакте, вконтакте'), 'http://vk.com/psycholog_skype'

app/views/layouts/head/_head.html.haml
%meta{content: 'vitalina.liane@gmail.com', name: 'author'}/
%meta{content: 'Vitalina Vakulchyk', name: 'author'}/
%meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{content: 'all', name: 'robots'}/
%meta{content: 'index, follow', name: 'robots'}/
%meta{content: @descr_head, name: 'description'}/
%meta{content: 'becf6957ba9d4519dcc2633c24ec215a', name: 'interkassa-verification'}/
<meta name="interkassa-verification" content="becf6957ba9d4519dcc2633c24ec215a" />
%meta{content: @keys, name: 'keywords'}/

%link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,300,600&subset=latin,cyrillic", :rel => "stylesheet", :type => "text/css"}/
%link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic", :rel => "stylesheet", :type => "text/css"}/

= render partial: 'layouts/head/ie_preview_meta'

= render partial: 'layouts/ie_link_prerender_prefetch'

= csrf_meta_tags
= stylesheet_link_tag 'application', media: 'all'
= render partial: 'layouts/head/head_css'
= javascript_include_tag 'application'

/[if IE]
  %script{type: 'text/javascript', src: 'html5'}

%title
  -# ■ 
  Психолог по Skype и E-mail -
  - if @title
    = @title
  - else
    Хочу счастья

app/views/layouts/head/_head_css.html.haml
/[if lt IE 7]
  :css
    * {
        margin: 0;
    }
    html, body {
        height: 100%;
        overflow: auto;
    }
    .wrapper {
        position: relative;
        width: 100%;
        height: 100%;
        overflow: auto;
    }
    .box {
        position: fixed;
        left: 10px;
        top: 180px;
    }
    * html .box {
        position: absolute;
    }

/[if lt IE 9]
  :css
    #psycologist {
      position: static;
    }

/[if lt IE 9]
  :css
    /*#block {
      background: #ffe190;
    }
    #main_block {
      background: #ffe190;
    }*/
    #list_description {
      margin-bottom: 2px;
    }
    #top_field {
      font-size: 190%;
    }
    A:hover {
      cursor: pointer;
    }
    .my-input-xlarge {
      border: 0;
      ie-dummy: expression(this.hidefocus=true);
    }

app/views/layouts/head/_ie_preview_meta.html.haml
%meta{content: "Хочу почувствовать счастье", name: "application-name"}/
%meta{content: "#95dd23", name: "msapplication-TileColor"}/
%meta{content: "preview/tiny.png", name: "msapplication-square70x70logo"}/
%meta{content: "preview/square.png", name: "msapplication-square150x150logo"}/
%meta{content: "preview/wide.png", name: "msapplication-wide310x150logo"}/
%meta{content: "preview/large.png", name: "msapplication-square310x310logo"}/

app/views/layouts/instruction/_products.html.haml
.k
  %b
    Чтобы приобрести видеозапись этого семинара:
  %ul
    %li
      Один
    %li
      Два
    = image_tag 'apple.jpeg', id: 'instruction_img_1', alt: '#'